[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = [
  'cd logipeek_frontend && npm install'
]

[phases.build]
cmds = [
  'cd logipeek_frontend && npm run build'
]

[start]
cmd = 'cd logipeek_frontend && npm run preview -- --port $PORT --host 0.0.0.0'