[phases.setup]
nixPkgs = ['nodejs_18', 'npm']

[phases.install]
cmds = [
  'npm install',
  'cd logipeek_backend && npm install'
]

[phases.build]
cmds = [
  'cd logipeek_backend && npm run build'
]

[start]
cmd = 'npm start'